[project]
name = "assignment-cover-pdf"
version = "0.1.0"
description = "Assignment Cover Page Generator"
authors = [
    {name = "Rahexa", email = "rahexa@example.com"}
]
requires-python = ">=3.11"
dependencies = [
    "Flask",
    "WeasyPrint",
    "python-docx",
    "pypdf",
    "gunicorn"
]
